project_name: test-go

before:
  hooks:
    - go mod tidy

builds:
  - binary: testgo
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64

  # - binary: testgo
  #   main: ./routingservice
  #   env:
  #     - CGO_ENABLED=0
  #   goos:
  #     - linux
  #     - windows
  #   goarch:
  #     - amd64



archives:
  - id: test-go
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    files:
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^chore:"
      - "^test:"
      - "^tests:"
