version: '3.9'

services:
  redis-server:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"

  mongodb:
    image: mongo:5
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test